--- 
- name: Simulate a task to fail on a host
  hosts: webserver
  tasks:
    - name: set a task to fail
      shell: /bin/false
    - name: set a task to run successfully
      shell: /bin/true
      notify: success
  handlers:
    - name: success
      debug: 
        msg: "This task has been executed successfully"
