---
- name: Verifying host variable
  hosts: server2
  tasks:
  - name: Testing first variable (http_port)
    debug:
      msg: "The HTTP PORT is {{ http_port }}"
  - name: Testing second variable (pkg)
    debug:
      msg: "The package name is {{ pkg }}"

# command :- [$ ansible-playbook playbook_1.yml]

---
- name: Verifying group variable
  hosts: db
  tasks:
  - name: Testing first variable (http_port)
    debug:
      msg: "The HTTP PORT is {{ http_port }}"
  - name: Testing second variable (pkg)
    debug:
      msg: "The package name is {{ pkg }}"

---
- hosts: server2
  vars:
    port_no: 80
    pkg_name: httpd
  gather_facts: no
  tasks:
  - debug:
      msg:
       - "The value of port is {{ port_no }}"
       - "The value of pkg is {{ pkg_name }}"
       - "The value of hostname is {{ inventory_hostname }}"
       - "Ansible version is {{ ansible_version }}"

---
- hosts: localhost
  vars:
    username: deepak
  tasks:
  - debug:
    msg: "USERNAME={{ username }}"

# commands :- [$ ansible-playbook variable-with-cmd-line.yml -e username=golinuxcloud]

---
 - name: Collect IPv4 address of eth0
   hosts: localhost
   tasks:
   - debug:
       msg:
         - "Method-1 {{ ansible_eth0.ipv4.address }}"
         - "Method-2 {{ ansible_eth0['ipv4']['address'] }}"
         - "Method-3 {{ ansible_eth0['ipv4'].address }}"
         - "Method-4 {{ ansible_eth0.ipv4['address'] }}"

---
 - name: Capture output of command
   hosts: localhost
   gather_facts: false
   tasks:
   - name: Collect ip address
     shell: "ifconfig eth0"

---
 - name: Capture output of command
   hosts: localhost
   gather_facts: false
   tasks:
   - name: Collect ip address
     shell: "ifconfig eth0"
     register: ip_addr
   - debug: var=ip_addr

---
 - name: Capture output of command
   hosts: localhost
   gather_facts: false
   tasks:
   - name: Collect ip address
     shell: "ifconfig eth0"
     register: ip_addr
   - debug: var=ip_addr.stdout

# Prompt for user input with vars_prompt
---
 - name: Prompt for user input
   hosts: localhost
   gather_facts: no
   vars_prompt:
     - name: user_name
       prompt: Enter your user name
       private: no
     - name: password
       prompt: Enter your password
       private: yes
   tasks:
     - debug:
         msg: "The username is {{ user_name}} and password is {{ password }}"

# command :- [$ ansible-playbook playbook_1.yml] ---> It will prompt to ask "Enter your user name: " & "Enter your password: "
