---
- name: with_items and selectattr equalto
  hosts: 127.0.0.1
  tasks:
  - name: add several users
    user:
      name: "{{ item }}"
      state: present
      groups: "wheel"
    with_items:
       - testuser1
       - testuser2
