---
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: install packages
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - apache2
        - ufw
        - mysql
