---
- name: Shell module example
  hsots: webservers
  tasks:
  - name: Run multiple commands
    shell: |
       date > /tmp/date.txt
       uptime > /tmp/uptime.txt
       echo "Hello World" > /tmp/hello.txt
