---
- name: Ansible archive Examples
  user: vagrant
  hosts: testserver
  tasks:
    - name: Compress Directory contents
      become: yes
      archive:
        path: /apps/tomcat
        dest: /apps/tomcat.tar.gz
        format: gz
