---
- name: Ansible archive Examples
  user: vagrant
  hosts: testserver
  tasks:
    - name: Compress Directory contents using ZIP
      become: yes
      archive:
        path: /apps/tomcat
        dest: /apps/tomcat-bkp.tar.zip
        format: zip
