---
- name: copy files to destination
  hosts: localhost
  connection: local
  tasks:
    - name: no force copy src.txt as dest.txt in the same dir 
      copy:
        src: files/src.txt
        dest: files/dest.txt
        force: no
      tags:
        - simple_copy_no_force
