---
- name: Ansible Copy Directory Example Local to Remote
  hosts: remoteserver
  tasks:
    - name: Copying the Directory and its contents
      become: true 
      copy:
        src: ~/Downloads/logos
        dest: /var/www/html
        owner: apache
        group: apache        
        mode: 0644
