---
- name: Replace line in file examples
  hosts: web

  handlers:
    - name: restart apache
      become: yes
      become_user: root
      service: name=httpd state=restarted

  tasks:

    - name: "Replacing the Fox with Formatting only in headline before closing of H2"
      become: yes
      become_user: root
      replace: 
        path: /var/www/html/index.html
        regexp: '[F|f]ox'
        replace: '<span style="color:crimson">Fox</span>'
        before: "</h2>"
        backup: yes

    - name: "Replacing the Grape with Formatting only in headline before closing of H2"
      become: yes
      become_user: root
      replace: 
        path: /var/www/html/index.html
        regexp: '[G|g]rape'
        replace: '<span style="color:purple"> Grape </span>'
        before: "</h2>"
        backup: yes   
      notify: restart apache
