---
- name: Ansible List Examples
  hosts: localhost
  tasks:
    - name: Create a List variable and print it
      set_fact: 
        Countries : ['India','Japan', 'Norway', 'Netherlands', 'Switzerland', 'Germany', 'United States of America']
    - name: Print the Countries before adding element
      debug: var=Countries
    - name: Add new element to Countries
      set_fact: 
        Countries: "{{ Countries + ['United Kingdom', 'Russia'] }}"
    - name: Print the Countries after adding element
      debug: var=Countries
