---
- name: Shell Examples
  hosts: testservers
  tasks:

  - name: Open /etc/password file
    become: yes
    shell:
       "cat password"
    args:
      chdir: "/etc" 
    register: fileout
    tags: fileout

  - debug: msg="{{ fileout.stdout-lines }}"
