---
- hosts: ansible_client.lab.com
  become: yes
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present
    tags: nginx_service
  - name: Check nginx service is running and enabled
    service:
      name: nginx
      state: started
      enabled: yes
    tags: nginx_service足足足足

# command :- [$ ansible-playbook playbook_2.yaml --tags "nginx_service"]
