---
- hosts: all
  tasks:
    - name: Create new users
      user:
        name: ''
        uid:  ''
        comment:  '' 
        state: present
      loop:
        - name: mike
          uid: 1001
          comment: Administrator
        - name: sandra
          uid: 1002
          comment: Techie

# Link :- https://www.cherryservers.com/blog/how-to-use-variables-in-ansible-playbooks
