---
- hosts: all
  vars:
    students:
        Alice:
          gender: female
          age: 21
          city: Boston
        Mark:
          gender: male
          age: 23
          city: Dallas
        Peter:
          gender: male
          age: 26
          city: Miami
  tasks:
  - name: Ansible Dictionaries Usage Example
    debug:
      msg: " A list of student details: "
