---
- name: tag
  hosts: all
  become_user: root

  tasks:
  - yum:
      name:
      - httpd
      - memcached
      state: present
    tags:
    - packages

  - template:
      src: templates/src.j2
      dest: /etc/foo.conf
    tags:
    - configuration
