---
- name: Ansible Tags
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "This is first task"
      tags:
        - first
        - general
    - debug:
        msg: "This is second task"
      tags: second
    - debug:
        msg: "This is third task"
      tags:
        - third
        - general
    - debug:
        msg: "This is fourth task"
      tags:
        - fourth
        - never

# command :- [$ ansible-playbook playbook_3.yml] - In output the 4th task will not be execute.
# So the fourth task was not executed here. But we can execute the fourth task by using --tags fourth
# command :- [$ ansible-playbook playbook_3.yml --tags fourth]
# In such case the "never" tag control is overwritten by the command line argument with a higher precedence.
