---
- name: Ansible Tags
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "This is first task"
      tags: first
    - debug:
        msg: "This is second task"
      tags: second
    - debug:
        msg: "This is third task"
      tags: third
    - debug:
        msg: "This is fourth task"
      tags: fourth

# command :- [$ ansible-playbook playbook_1.yaml]
# command :- [$ ansible-playbook playbook_1.yaml --tags first]
# command :- [$ ansible-playbook playbook_1.yaml --tags first,third]
# command :- [$ ansible-playbook playbook_1.yaml --skip-tags fourth]
