# same tag name for multiple tasks so that with a single tag name we can execute multiple tasks
---
- name: Ansible Tags
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "This is first task"
      tags:
        - first
        - general
    - debug:
        msg: "This is second task"
      tags: second
    - debug:
        msg: "This is third task"
      tags:
        - third
        - general
    - debug:
        msg: "This is fourth task"
      tags: fourth

# command :- [$ ansible-playbook playbook_2.yml --tags general]
