---
- hosts: 172.31.12.119
  become: True
  tasks:
    - name: Install packages
      yum:
        name: httpd
        state: present
    - name: Enable apache on reboot
      service:
        name: httpd
        enabled: True
    - name: Install git
      yum:
        name: git
        state: present
    - name: Deploy website from git
      become: yes
      git:
        repo: https://github.com/javahometech/javahome-app
        dest: /var/www/html/
    - name: restart apache
      service:
        name: httpd
        state: restarted
