# print Variables using Debug module
---
- name: Ansible debug module in action
  hosts: all
  vars:
          greetings: Hello World!
          site: Linuxtechi
  tasks:
          - name: Print the value of a variable
            debug:
              msg: "{{ greetings }}, Welcome to {{ site }}."

# Link :- https://www.linuxtechi.com/use-debug-module-ansible-playbook/
