---
- name: Example 1
  hosts: all
  remote_user: devops
  become: true
  tasks:
  - name: Print Message
    debug:
      msg: "Hello, this is example 1"  
  - name: including a task from file
    include_tasks: user_creation.yml
