---
- hosts: 127.0.0.1
  tasks:
   - name: System Uptime
     command: uptime
     register: uptime
   - name: System Hostname
     command: hostname
     register: host
   - debug: var={{ item }}
     loop:
       - uptime.stdout
       - host.stdout
