---
- hosts: webservers 
  become: true
  tasks:
  - name: Copy Tomcat ZIP file to install location Short description of the task
    copy: src=/home/ansible/niranjan/apache-tomcat-8.5.31.tar.gz dest=/opt/niranjan/tomcat
