---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
  - name: Installapacheserver
    package:
      name: httpd
      state: latest
    when: (ansible_facts['os_family']=="Debian")and(ansible_facts['ansible_distribution_major_version']==10)
