---
- name: Install Apache on RHEL server
  hosts: webserver
  tasks:
    - name: Install the latest version of Apache
      dnf:
        name: httpd
        state: latest

    - name: Configure Apache 
      copy:
        src: /home/cherry/Documents/index.html
        dest: /var/www/html
        owner: apache
        group: apache        
        mode: 0644

      notify:
      - Configure Firewall
      - Start Apache   


  handlers:

     - name: Start Apache
       service:
         name: httpd
         state: started

     - name: Configure Firewall
       firewalld:
         permanent: yes
         immediate: yes
         service: http
         state: enabled

# Link :- https://www.cherryservers.com/blog/how-to-define-and-use-handlers-in-ansible-playbooks
