---
- hosts: aws
  tasks:
   - name: Install Nginx
     apt: name=nginx state=latest update_cache=true
     notify:
      - Start Nginx

  handlers:
   - name: Start Nginx
     service: name=nginx state=started
