# Duplicate Tasks - If two or more tasks are defined with the same name only the first task read by ansible will run ignoring all other tasks with the same name.
---
- name: Handlers testing
  hosts: ubuntu.anslab.com
  gather_facts: false
  tasks:
    - name: Get the hostname
      shell: hostname -s
      register: hostname
      notify: print hostname
    - name: Get IP address of the hostname
      shell: hostname -I
      register: IP
      notify: print hostname
  handlers:
    - name: print hostname
      debug:
        var: IP.stdout
    - name: print hostname
      debug:
       var: hostname.stdout

# Link :- https://ostechnix.com/use-handlers-in-ansible-playbooks/
