---
- name: this is our first play.
  hosts: webserver
  sudo: yes
  tasks: 
    - name: "create a dummy file on websever1"
      lineinfile: dest=/etc/resolv.conf line="nameserver 8.8.8.8"

# running this playbook, need to provide the password for the sudo privilege :- [$ ansible-playbook playbook_1.yaml --ask-become-pass]
